
# This is the configuration file for single documentations
# The thing you must specify is the src_doc, dest_lang, split_colon
# others will use the default!
[type]
type = single-file

[document_path]
src_doc = README.md
dest_doc = 

[langs_settings]
dest_lang = zh-cn
split_colon = .

