
# This is the configuration file for single documentations
# The thing you must specify is the src_doc, dest_lang, split_colon
# others will use the default!
[type]
anatype = doc-tree

[document_path]
src_dir = tests\doc_test
dest_type = all-in-on
dest_dir = 

[langs_settings]
dest_lang = zh-cn
split_colon = .

